### ISSUE TITLE
 NoC RTL  simulaton

### ISSUE THREAD

**Issue by Elena32061** [ucb-bar/constellation#26]
Hi sir, your work is really amazing. I also completed a NoC with chisel, and the basic unit passed the unit test of chiseltest, but I don't know how to do RTL simulation test for the complete NoC written in chisel language. I would like to ask you, how did you test when you completed the NOC that was not integrated into the chipyard framework.

**Comment by jerryz123** [comment]
Integration with Chipyard has already been completed, and will be released in the next Chipyard release before October 1st.

**Comment by jerryz123** [comment]
I realize I misunderstood your question. 

I wrote Chisel testbenches for the entire network, these were basic traffic injectors that would load the network.

**Comment by Elena32061** [comment]
Thank you！


-----原始邮件-----
发件人:"Jerry Zhao" ***@***.***>
发送时间:2022-09-20 05:57:50 (星期二)
收件人: ucb-bar/constellation ***@***.***>
抄送: Elena ***@***.***>, Author ***@***.***>
主题: Re: [ucb-bar/constellation] NoC RTL simulaton (Issue #26)



I realize I misunderstood your question.

I wrote Chisel testbenches for the entire network, these were basic traffic injectors that would load the network.
