### ISSUE TITLE
May I ignore the "[error] Picked up JAVA_TOOL_OPTIONS" error?

### ISSUE THREAD

**Issue by manili** [ucb-bar/constellation#41]
Hi,
I'm trying to test constellation using the instructions [here](https://constellation.readthedocs.io/en/latest/Introduction/SimpleTests.html#chipyard-standalone-testing). But I'm getting the following error:

```
[error] Picked up JAVA_TOOL_OPTIONS: -Xmx8G -Xss8M -Dsbt.supershell=false -Djava.io.tmpdir=/home/manili/Desktop/chipyard/.java_tmp
```

Also, there is no `constellation.test.TestHarness.TestConfig00.top.v` in the folder. Is the error root cause of missing `*.top.v` file?

**Comment by jerryz123** [comment]
You may ignore the [error] message, that's a fake message.

For the second message, I believe its due to changes in the recent Chipyard. I need to update the documentation. Now all the NoC RTL should be deposited in a directory called `gen-collateral`. I'll leave this issue open until I do that.
