### ISSUE TITLE
Question: What are the parameters in the example Butterfly config?

### ISSUE THREAD

**Issue by JL102** [ucb-bar/constellation#46]
Hi,

Quick question. I'm new to the concept of butterfly networks. In the Butterfly topology example (https://constellation.readthedocs.io/en/latest/Configuration/Topologies.html), what are the values of kAry and nFly to generate the example? Is it the same as the Wikipedia example (https://en.wikipedia.org/wiki/Butterfly_network#/media/File:Butterfly_Network_Routing.jpg, they say the degree is 4) but with one fewer stages?

Also, the direction of data flow in the Wikipedia example seems unclear. Does the direction not matter for a Butterfly network?

Thanks!

**Comment by jerryz123** [comment]
There might be a off-by-1 from the Wikipedia example, but the meaning should be the same.

The default butterfly example here generates a unidirectional butterfly.

**Comment by JL102** [comment]
So would kAry = 4 and nFly = 3 generate a topology equivalent to the diagram? Just wanna make sure I understand it.

**Comment by jerryz123** [comment]
The one in the docs diagram is `kAry=2, nFly=3` I believe

**Comment by JL102** [comment]
Got it, thanks for the answer/help!
