### ISSUE TITLE
Failed: Running Minimal-Standalone Testing

### ISSUE THREAD

**Issue by furoge** [ucb-bar/constellation#50]
Greetings

I ran the minimal-standalone testing following the insturctions:

cd constellation
CONSTELLATION_STANDALONE=1 sbt "testOnly constellation.NoCTest00"

And i got:

❱ CONSTELLATION_STANDALONE=1 sbt "testOnly constellation.NoCTest00"
[info] welcome to sbt 1.4.9 (Temurin Java 1.8.0_382)
[info] loading project definition from /home/tom/basement/hw/sbt_play/dpdnc/constellation/project
[info] loading settings for project constellation from build.sbt ...
[info] set current project to constellation (in build file:/home/tom/basement/hw/sbt_play/dpdnc/constellation/)
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading edu.berkeley.cs:rocketchip_2.13:1.6.0
[error]   Not found
[error]   Not found
[error]   not found: /home/tom/.ivy2/local/edu.berkeley.cs/rocketchip_2.13/1.6.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/edu/berkeley/cs/rocketchip_2.13/1.6.0/rocketchip_2.13-1.6.0.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3525)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:750)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading edu.berkeley.cs:rocketchip_2.13:1.6.0
[error]   Not found
[error]   Not found
[error]   not found: /home/tom/.ivy2/local/edu.berkeley.cs/rocketchip_2.13/1.6.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/edu/berkeley/cs/rocketchip_2.13/1.6.0/rocketchip_2.13-1.6.0.pom
[error] Total time: 4 s, completed Jul 25, 2023 3:14:32 PM

and my build.sbt (which i did not change):

name := "constellation"
version := "0.1"
scalaVersion := "2.13.10"

scalacOptions ++= Seq(
  "-language:reflectiveCalls",
  "-deprecation",
  "-feature"
)

val standalone = sys.env.get("CONSTELLATION_STANDALONE").isDefined

// SNAPSHOT repositories
libraryDependencies ++= (if (standalone) {
  Seq(
    "edu.berkeley.cs" %% "rocketchip" % "1.6.0",
    "edu.berkeley.cs" %% "cde" % "1.6.0",
    "edu.berkeley.cs" %% "rocket-macros" % "1.6.0",
    "edu.berkeley.cs" %% "chiseltest" % "0.5.4" % "test"
  )
} else {
  Nil
})

addCompilerPlugin("edu.berkeley.cs" % "chisel3-plugin"
  % (if (standalone) "3.5.6" else "3.5.6") cross CrossVersion.full)

import Tests._

Test / fork := true
Test / testGrouping := (Test / testGrouping).value.flatMap { group =>
   group.tests.map { test =>
      Group(test.name, Seq(test), SubProcess(ForkOptions()))
   }
}
concurrentRestrictions := Seq(Tags.limit(Tags.ForkedTestGroup, 72))

Looks like i was not able to download files from edu.berkeley.cs:rocketchip_2.13:1.6.0 and i'm not sure about it

Please help and thanks in advance!

**Comment by jerryz123** [comment]
Did you run the `publishLocal` command in the local fork of rocket-chip, as the docs suggest?

**Comment by furoge** [comment]
@jerryz123 
Hi,
NO! And I'm going to do so!
Thanks for your help!!
