### ISSUE TITLE
constellation/src/main/scala/channel/Nodes.scala:4:8: object SourceInfo is not a member of package chisel3.experimental

### ISSUE THREAD

**Issue by wudehua2016** [ucb-bar/constellation#73]
error was that
[error] /home/riscv/noc/constellation/src/main/scala/channel/Nodes.scala:4:8: object SourceInfo is not a member of package chisel3.experimental
[error] import chisel3.experimental.SourceInfo
[error]        ^
[error] /home/riscv/noc/constellation/src/main/scala/channel/Channel.scala:7:8: object ClockCrossingType is not a member of package freechips.rocketchip.prci
[error] import freechips.rocketchip.prci.{ClockCrossingType, NoCrossing}
[error]        ^
[error] /home/riscv/noc/constellation/src/main/scala/channel/Nodes.scala:13:75: not found: type SourceInfo
[error]   def edge(pd: EmptyParams, pu: ChannelParams, p: Parameters, sourceInfo: SourceInfo) = {
[error]                                                                           ^
[error] /home/riscv/noc/constellation/src/main/scala/channel/Nodes.scala:42:82: not found: type SourceInfo
[error]   def edge(pd: EmptyParams, pu: IngressChannelParams, p: Parameters, sourceInfo: SourceInfo) = {
[error]                                                                                  ^
[error] /home/riscv/noc/constellation/src/main/scala/channel/Nodes.scala:54:81: not found: type SourceInfo
[error]   def edge(pd: EmptyParams, pu: EgressChannelParams, p: Parameters, sourceInfo: SourceInfo) = {
[error]                                                                                 ^
[error] /home/riscv/noc/constellation/src/main/scala/channel/Parameters.scala:7:8: object ClockCrossingType is not a member of package freechips.rocketchip.prci
[error] import freechips.rocketchip.prci.{ClockCrossingType, NoCrossing}
[error]        ^
[error] /home/riscv/noc/constellation/src/main/scala/channel/Parameters.scala:26:17: not found: type ClockCrossingType
[error]   crossingType: ClockCrossingType = NoCrossing,
[error]                 ^
[error] /home/riscv/noc/constellation/src/main/scala/channel/Parameters.scala:26:37: not found: value NoCrossing
[error]   crossingType: ClockCrossingType = NoCrossing,

how can i fix that?

**Comment by jerryz123** [comment]
Unfortunately the standalone build of constellation is broken. Constellation now must be built through Chipyard, using the chipyard-standalone or chipyard-soc flows.
