### ISSUE TITLE
How to run the tests in test folder

### ISSUE THREAD

**Issue by pointerliu** [ucb-bar/constellation#76]
It appears that Constellation cannot be run independently. 
How can I execute the tests located in the [test folder](https://github.com/ucb-bar/constellation/blob/master/src/test/scala/constellation/NocTests.scala) now?

I am attempting to run `sbt "project constellation" test` in the Chipyard environment, but it seems to require a large amount of memory. Did I miss anything ?

Is there a recommended approach for running these tests efficiently?

**Comment by jerryz123** [comment]
Running it through Chipyard is the best way. 

`make SUB_PROJECT=constellation CONFIG=TestConfig00 run-binary BINARY=none`
