### ISSUE TITLE
Running a Simple Evaluation

### ISSUE THREAD

**Issue by SoCScholar** [ucb-bar/constellation#78]
[Running a Simple Evaluation](https://github.com/ucb-bar/constellation/blob/8dab95780b69c33da8b5544d5939850098d55481/docs/source/Evaluation/index.rst#running-a-simple-evaluation 
)

```
cd chipyard/sims/verilator
make SUB_PROJECT=constellation BINARY=none CONFIG=EvalTestConfig00 MODEL=EvalHarness run-binary-debug
```

Hi i get issues like below while Running a Simple Evaluation. 

Is there any bug in it ? or it may be old: Traffic evaluations are best run in **Chipyard-standalone mode**. 

I try to run inside **verilator**

` chipyard/sims/verilator `

```
/home/himal/1_Gitlab_Software_code/NoC_Constellation_Rocketchip/1_chipyard/chipyard/sims/verilator/generated-src/constellation.test.EvalHarness.EvalTestConfig00/gen-collateral/netrace.c:767:17: note: in expansion of macro 'nt_error'
  767 |                 nt_error( "dumping NULL packet" );
      |                 ^~~~~~~~
make[1]: *** [VTestDriver.mk:67: netrace.o] Error 1
make[1]: Leaving directory '/home/himal/1_Gitlab_Software_code/NoC_Constellation_Rocketchip/1_chipyard/chipyard/sims/verilator/generated-src/constellation.test.EvalHarness.EvalTestConfig00/constellation.test.EvalHarness.EvalTestConfig00.debug'
make: *** [Makefile:213: /home/himal/1_Gitlab_Software_code/NoC_Constellation_Rocketchip/1_chipyard/chipyard/sims/verilator/simulator-constellation.test-EvalTestConfig00-debug] Error 2
(/home/himal/1_Gitlab_Software_code/NoC_Constellation_Rocketchip/1_chipyard/chipyard/.conda-env) himal@himal-ThinkPad:~/1_Gitlab_Software_code/NoC_Constellation_Rocketchip/1_chipyard/chipyard/sims/verilator$ 

````

**Comment by jerryz123** [comment]
You didn't post enough of the terminal output to capture the actual error

**Comment by jerryz123** [comment]
Do you have access to a commercial simulator tool like VCS?

**Comment by jerryz123** [comment]
Unfortunately not. I could reproduce the error you see, but I was not able to come up with a quick solution.

If add `-fpermissive` to the SIM_CXXFLAGS in common_sim_flags.mk, you get past the error you posted, but you hit a linker error later. I was unable to come up with a solution to the linker error.

**Comment by jerryz123** [comment]
Yes, I don't know how to resolve this error in a clean way. If you dig into the Verilator makefiles, you can see this is because it generates the linker command as `TrafficEval.o netrace.o`, when it needs to be `netrace.o TrafficEval.o`. 

Perhaps if you reorder it manually, it will work. But a better solution is to figure out how to make Verilator use the correct file order.

**Comment by jerryz123** [comment]
I meant the VTestharness.mk verilator-generated makefile, but you are right, in that the right solution would be investigating how Verilator is generating the linker command
